spring:
  application:
    name: xml-to-json-publisher

disk-saver:
  path: ${DISK_SAVER_PATH}

async:
  pool-size: ${ASYNC_POOL_SIZE}

management:
  endpoints:
    web:
      exposure:
        include: "metrics,prometheus"

